#  Configuration for basic scaled inflation
# Note that these are the variable names, not the command parser flags
modelName='XM13_nacncoop'
soma_autoinflate=true
dendrite_autoinflate=false
ASA_fromsoma=true
dendrite_fromsoma=true
noparallel=true
