#  Configuration for basic scaled inflation
# Note that these are the variable names, not the command parser flags
modelName='XM13_nacncoop'  # decoration data table in 
fullhocfile=true  # use "full" hoc file
soma_autoinflate=true  # inflat the soma according to the excel table (see 'wheres_my_data.toml"")
dendrite_autoinflate=true  # inflate the dendrite by the table
ASA_fromsoma=true  # inflate the asa by the same amount as the soma
dendrite_fromsoma=false  # if true, inflate the dendrite the same as the soma
save_all_sections=false # 
SGCmodelType='cochlea'  # which sgc model to run
SRType='HS'
ANSynapseType='multisite'
dB=30.0
F0=16000.0
pip_duration=0.2
soundtype="SAM"  # or "tonepip" or "noise"
fmod=100.0
dmod=100.0
seed=9
Parallel=true
