#  Configuration for basic scaled inflation
# Note that these are the variable names, not the command parser flags
modelName='XM13_nacncoop'  # decoration data table in 
fullhocfile=true  # use "full" hoc file
soma_autoinflate=false  # inflat the soma according to the excel table (see 'wheres_my_data.toml"")
dendrite_autoinflate=false  # inflate the dendrite by the table
ASA_fromsoma=false  # inflate the asa by the same amount as the soma
dendrite_fromsoma=false  # if true, inflate the dendrite the same as the soma
save_all_sections=true # 
SGCmodelType='cochlea'  # which sgc model to run
SRType='HS'
ANSynapseType='multisite'
dB=50.0
F0=16000.0
seed=9
Parallel=false


