#  Configuration for basic scaled inflation
# Note that these are the variable names, not the command parser flags
modelName='XM13_nacncoop'  # decoration data table in 
full=true  # use "full" hoc file
soma_autoinflate=false  # inflat the soma according to the excel table (see 'wheres_my_data.toml"")
dendrite_autoinflate=false  # inflate the dendrite by the table
ASA_fromsoma=true  # inflate the asa by the same amount as the soma
dendrite_fromsoma=false  # if true, inflate the dendrite the same as the soma
sgc_model='cochlea'  # which sgc model to run
SRType='HS'
r=1
d=50.0
f=4000.0

noparallel=true  # better for debugging

# noparallel=true
