# filenames and paths
# Use this to set the directories and paths where you put the data files
# that can drive the simulations. 
# This file is mostly used by cell_config.py, but it is also imported
# elsewhere rather than harcoding some of the paths.
#
# Read this file directly using:
# import toml
# with open("wheres_my_data.toml", "r") as fh:
#   config = toml.load(fh)
#   config["disk"] must be prepended to some of the paths
#
# or better, construct the paths by calling:
# from get_data_paths import get_data_paths
# config = get_data_paths()
# (this sets the disk)

# Dec 2020: Move simulation result storage off to RAID or other external disk for space reasons.

disk = "/Volumes/T7"  # define the disk or path to the directory where the data directory can be found
shareddatadisk = "/Volumes/T7"  # where to store shared results related to manuscript
# disk = "/Volumes/Pegasus_002"

baseDataDirectory = "VCN-SBEM-Data" # "/Users/pbmanis/Desktop/Python/VCN-SBEM-Data"
cellDataDirectory = "VCN-SBEM-Data/VCN_Cells" #"/Users/pbmanis/Desktop/Python/VCN-SBEM-Data/VCN_Cells"
revcorrDataDirectory = "VCN_Revcorr_Summaries" # "/Users/pbmanis/Desktop/Python/VCN-SBEM-Data/VCN_Revcorr_Summaries"
baseMorphologyDirectory = "MorphologyData/VCN" # "/Users/pbmanis/Desktop/Python/VCN-SBEM-Data/MorphologyData/VCN"
codeDirectory="./vcnmodel"
pngDirectory="VCN-CellImages-1-2020/Bushy_Cells"  # png files, in baseDataDirectory
impedanceDirectory="Impedance_Calculations"  # Zin calculations in cellDataDirectory
figureIntermediateDirectory="IntermediateAnalyses"
figureDirectory="SBEM-paper Figures"
# dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_pbm_14Oct2019_v1.xlsx'
# dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_6_March_2020.xlsx'
# dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_2_April_2020.xlsx'

# most recent table. Note that the table has been annotated a few times since the stated date
# of the file. These include: updating estimage of c18's soma and dendrite area, and
# updating synapse counts from Matthew Kersting.
#dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_29_June_2020.xlsx'
#dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_17_June_2021.xlsx'  # updated for cell 18

dendriteQualityFile = 'Dendrite_Quality_and_Surface_Areas_for_Sims_Cleaned_8-30-2022.xlsx'  # updated for cell 18

# names of excel tabs in the dendrite quality file
asaData = "Input_ASA_FromautoASA.py"
asaHeaderSkip = 0
SomaAndDendriteData = "SomaDendrite_Summary"

