# filenames and paths
# Use this to set the directories and paths where you put the data files
# that can drive the simulations. 
# This file is mostly used by cell_config.py, but it is also imported
# elsewhere rather than harcoding some of the paths.
#
# Read this file as:
# import toml
# config = toml.load(open("wheres_my_data.toml", "r"))

baseDataDirectory = "/Users/pbmanis/Desktop/Python/VCN-SBEM-Data"
cellDataDirectory = "/Users/pbmanis/Desktop/Python/VCN-SBEM-Data/VCN_Cells"
baseMorphologyDirectory = "/Users/pbmanis/Desktop/Python/VCN-SBEM-Data/MorphologyData/VCN"
codeDirectory="/Users/pbmanis/Desktop/Python/vcnmodel"
pngDirectory="VCN-CellImages-1-2020/Bushy_Cells"  # png files
# dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_pbm_14Oct2019_v1.xlsx'
# dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_6_March_2020.xlsx'
# dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_2_April_2020.xlsx'
dendriteQualityFile = 'Dendrite Quality and Surface Areas_comparisons_29_June_2020.xlsx'

# names of excel tabs in the dendrite quality file
# asaData = "Input_ASA_FromASAProtocol(Holco"
# asaHeaderSkip = 3
asaData = "Input_ASA_FromautoASA.py"
asaHeaderSkip = 0
SomaAndDendriteData = "SomaDendrite_Summary"

