# tagstring should not have spaces in it - use underscores or dashes
tagstring = ""  # leave empty for now
# Testing for annotated configuration files
cellType = "Bushy"
modelName = "XM13"
modelType = "II"
soma_autoinflate = 1
dendrite_autoinflate = 1
usedefaulthoc = 1
runProtocol = 'runANPSTH'
F0 = 16000.0
dB = 50.0
soundtype = "SAM"
run_duration = 1.0
pip_duration = 0.8
fmod = 100.0
dmod = 100.0
SRType = "MS"
ANSynapseType = "multisite"
ANSynapticDepression = 1
SGCmodelType = "cochlea"
nReps = 20
